version: "1.50.0"

run:
  timeout: 5m
  go: '1.21'
  allow-parallel-runners: true

linters:
  enable:
    - gofmt
    - goimports
    - govet
    - staticcheck
    - errcheck
    - ineffassign
    - gosimple
    - typecheck
    - unused
    - misspell
    - revive

linters-settings:
  revive:
    rules:
      - name: var-naming
        severity: warning
      - name: exported
        severity: warning
      - name: package-comments
        severity: warning

  gofmt:
    simplify: true

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
        - gosec