# golangci-lint configuration
run:
  timeout: 3m
  go: '1.24'

issues:
  max-issues-per-linter: 0
  max-same-issues: 0

linters:
  enable:
    - gofmt
    - govet
    - errcheck
    - staticcheck
    - ineffassign
    - misspell
    - gosec
    - revive
