version: "2"

run:
  timeout: 3m
  go: '1.24'
  allow-parallel-runners: true

linters:
  enable:
    - gofmt
    - goimports
    - govet
    - staticcheck
    - errcheck
    - ineffassign
    - gosimple
    - unused
    - misspell
    - revive

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
