version: "2"

run:
  timeout: 3m
  go: '1.24'

issues:
  max-issues-per-linter: 0
  max-same-issues: 0

linters:
  enable:
    - govet
    - errcheck
    - staticcheck
    - ineffassign
    - unused
    - misspell
    - gosec

# reviveは厳しすぎるので無効化
  disable:
    - revive
