name: cicd
on:
  push:
    branches:
      - main
  pull_request:
permissions:
  contents: read
jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v4
        with:
          go-version: '1.21'
      - uses: actions/checkout@v3
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest
          working-directory: src/video-converter
          args: -v
  deploy:
    name: deploy
    needs: golangci
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v4
        with:
          go-version: '1.21'
      - uses: actions/checkout@v3
      - name: deploy to Cloud functions
        env:
          JSON_ENCODED: ${{ secrets.GCP_YOUTUBE_CONF_DEPLOY }}
          GOOGLE_APPLICATION_CREDENTIALS : credentials.json
        run: |
          cd src/video-converter
          echo $JSON_ENCODED | base64 --decode > credentials.json
          echo credentials.json
          gcloud functions deploy video-converter --gen2 --runtime=go120 --region=asia-northeast1 --entry-point=VideoConverter --trigger-http --allow-unauthenticated --project youtube-video-configurator