name: PR Checks
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  golangci-lint:
    name: lint go
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v4
        with:
          go-version: '1.24'
      - uses: actions/checkout@v4

      - name: lint video-converter
        uses: golangci/golangci-lint-action@v7
        with:
          version: latest
          working-directory: src/video-converter
          args: --config=../../configs/.golangci.yaml -v

      - name: lint converter-starter
        uses: golangci/golangci-lint-action@v7
        with:
          version: latest
          working-directory: src/convert-starter
          args: --config=../../configs/.golangci.yaml -v

      - name: lint blog-post
        uses: golangci/golangci-lint-action@v7
        with:
          version: latest
          working-directory: src/blog-post
          args: --config=../../configs/.golangci.yaml -v
          
      - name: lint short-upload
        uses: golangci/golangci-lint-action@v7
        with:
          version: latest
          working-directory: src/short-upload
          args: --config=../../configs/.golangci.yaml -v

  unit-test:
    name: test go
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v4
        with:
          go-version: '1.24'
      - uses: actions/checkout@v4
      
      - name: test blog-post 
        working-directory: src/blog-post
        run: go test -v -cover ./...
        
      - name: test video-converter
        working-directory: src/video-converter
        run: go test -v -parallel 4 -cover ./...
        
      - name: test short-upload
        working-directory: src/short-upload
        run: go test -v -cover ./...

  go-mod-check:
    name: Check Go Modules
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Check go.mod tidy/verify (blog-post)
        working-directory: src/blog-post
        run: |
          go mod tidy
          go mod verify
      - name: Check go.mod tidy/verify (convert-starter)
        working-directory: src/convert-starter
        run: |
          go mod tidy
          go mod verify
      - name: Check go.mod tidy/verify (video-converter)
        working-directory: src/video-converter
        run: |
          go mod tidy
          go mod verify
      - name: Check go.mod tidy/verify (short-upload)
        working-directory: src/short-upload
        run: |
          go mod tidy
          go mod verify

  # gosec:
  #   name: gosec security scan
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v4
  #     - name: Install gosec
  #       run: go install github.com/securego/gosec/v2/cmd/gosec@latest
  #     - name: Run gosec (blog-post)
  #       working-directory: src/blog-post
  #       run: ~/go/bin/gosec ./...
  #     - name: Run gosec (convert-starter)
  #       working-directory: src/convert-starter
  #       run: ~/go/bin/gosec ./...
  #     - name: Run gosec (video-converter)
  #       working-directory: src/video-converter
  #       run: ~/go/bin/gosec ./...
  #     - name: Run gosec (short-upload)
  #       working-directory: src/short-upload
  #       run: ~/go/bin/gosec ./...

  gofmt:
    name: gofmt check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Check gofmt (blog-post)
        working-directory: src/blog-post
        run: test -z "$(gofmt -l .)" || (echo 'gofmt error' && exit 1)
      - name: Check gofmt (convert-starter)
        working-directory: src/convert-starter
        run: test -z "$(gofmt -l .)" || (echo 'gofmt error' && exit 1)
      - name: Check gofmt (video-converter)
        working-directory: src/video-converter
        run: test -z "$(gofmt -l .)" || (echo 'gofmt error' && exit 1)
      - name: Check gofmt (short-upload)
        working-directory: src/short-upload
        run: test -z "$(gofmt -l .)" || (echo 'gofmt error' && exit 1)

  go-build:
    name: go build check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build blog-post
        working-directory: src/blog-post
        run: go build ./...
      - name: Build convert-starter
        working-directory: src/convert-starter
        run: go build ./...
      - name: Build video-converter
        working-directory: src/video-converter
        run: go build ./...
      - name: Build short-upload
        working-directory: src/short-upload
        run: go build ./...

  terraform-fmt:
    name: Terraform fmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.11.0
      - name: Terraform fmt check
        run: terraform fmt -check -recursive infra

  trivy:
    name: scan IaC config
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v4

      - name: Install trivy
        uses: aquasecurity/setup-trivy@v0.2.3

      - name: Run trivy (Terraform IaC config check)
        run: |
          trivy config --severity CRITICAL ./infra

  lint-makefile:
    name: lint Makefile
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Check Makefile syntax
        run: make -n || (echo 'Makefile syntax error' && exit 1)

  # gitleaks:
  #   name: gitleaks secret scan
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v4
  #     - name: Run gitleaks
  #       uses: gitleaks/gitleaks-action@v1.6.0
  #       with:
  #         args: --source .
